local opts = { buffer = bufnr, remap = false }
vim.api.nvim_set_keymap("n", "<leader>cjr", "JavaRunnerRunMain", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>cjb", "JavaBuildBuildWorkspace", { noremap = true })
vim.keymap.set("n", "K", function()
	vim.lsp.buf.hover()
end, opts)
vim.keymap.set("n", "<leader>ls", function()
	vim.lsp.buf.workspace_symbol()
end, opts)
vim.keymap.set("n", "<C-d>", function()
	vim.diagnostic.open_float()
end, opts)
vim.keymap.set("n", "<leader>ld", function()
	vim.diagnostic.open_float()
end, opts)
vim.keymap.set("n", "]d", function()
	vim.diagnostic.goto_next()
end, opts)
vim.keymap.set("n", "[d", function()
	vim.diagnostic.goto_prev()
end, opts)
vim.keymap.set("n", "<leader>lsa", function()
	vim.lsp.buf.code_action()
end, opts)
vim.keymap.set("n", "<leader>lsr", function()
	vim.lsp.buf.references()
end, opts)
vim.keymap.set("n", "<leader>li", function()
	vim.lsp.buf.implementation()
end, opts)
vim.keymap.set("n", "<leader>lt", function()
	vim.lsp.buf.type_definition()
end, opts)
vim.keymap.set("n", "<leader>lr", function()
	vim.lsp.buf.rename()
end, opts)
vim.keymap.set("n", "<C-Space>", function()
	vim.lsp.buf.signature_help()
end, opts)
vim.keymap.set("n", "<S-Space>", function()
	vim.lsp.buf.hover()
end, opts)
vim.keymap.set("n", "<leader>gd", function()
	vim.lsp.buf.definition()
end, opts)
vim.keymap.set("n", "<leader>gt", function()
	vim.lsp.buf.type_definition()
end, opts)
vim.keymap.set("n", "<leader>td", "<cmd>Telescope diagnostics<CR>", opts)
vim.keymap.set("n", "<leader>cf", function()
	vim.lsp.buf.format()
end, opts)
vim.keymap.set("n", "<S-h>", "<cmd>CommentToggle<CR>", opts)
vim.keymap.set("n", "<leader>cf", vim.lsp.buf.format)
