local opts = { noremap = true, silent = true }

local diffview = require("diffview")

vim.keymap.set({ "n", "v" }, "gith", function()
	local input = vim.fn.input("file to display history (blank for all files, % for current file): ")
	vim.cmd("DiffviewFileHistory")
end, opts)
vim.keymap.set("n", "gitf", function()
	local input = vim.fn.input("(blank for current: ")
	vim.cmd("DiffviewFileHistory %")
end, opts)
vim.keymap.set("n", "gito", function()
	local input = vim.fn.input("Commit hash (blank for current: ")
	vim.cmd("DiffviewOpen " .. input)
end, opts)
vim.keymap.set("n", "gitc", function()
	vim.cmd("DiffviewClose")
end, opts)
vim.keymap.set("n", "gitt", function()
	vim.cmd("DiffviewToggleFiles")
end, opts)
vim.keymap.set("n", "gitr", function()
	vim.cmd("DiffviewRefresh")
end, opts)
vim.keymap.set("n", "gitu", function()
	vim.cmd("DiffviewFocusFiles")
end, opts)
